version: "3.8"
services:
  app-prod:
    build: ./app
    environment:
      - DATABASE_URL=postgresql://user:password@postgres-prod:5432/samoey_copilot_prod
      - REDIS_URL=redis://redis-prod:6379/0
    ports:
      - "8000:8000"
    restart: unless-stopped
  frontend-prod:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
  postgres-prod:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=samoey_copilot_prod
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    restart: unless-stopped
  redis-prod:
    image: redis:7-alpine
    volumes:
      - redis_prod_data:/data
    restart: unless-stopped
volumes:
  postgres_prod_data:
  redis_prod_data:
