version: "3.8"
services:
  app-test:
    build: ./app
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - REDIS_URL=redis://redis-test:6379/1
    depends_on:
      - redis-test
    command: pytest
  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
