name: Deploy All Platforms
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: macos-11.7.10
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        brew install pnpm
        pnpm install -g electron-builder

    - name: Deploy Packages  
      run: |
        chmod +x ./deploy-all.sh
        ./deploy-all.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:  
        name: release-packages
        path: |
          ./outputs/web/
          ./outputs/ios/
          ./outputs/macos/

    - name: Trigger OTA Update
      uses: actions/github-script@v6
      with:
        script: |
          await github.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: 'ota_update',
            client_payload: {
              ref: context.ref
            }
          })
